[versions]
agp = "8.10.1"
kotlin = "2.0.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.8.0"
activityKtx = "1.6.1"
fragment = "1.5.6"
navigation = "2.5.3"
navigationUI = "2.5.3"
viewModel = "2.5.1"
liveData = "2.5.1"
constraintlayout = "2.2.1"
viewpager2 = "1.0.0"
retrofit = "2.9.0"
glide = "4.16.0"
room = "2.5.1"
koin = "3.3.0"
ksp = "2.0.21-1.0.28"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx"}
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUI" }
livecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx",version.ref = "viewModel" }
livecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "liveData" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide"}
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}
retrofit-gson-factory = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit"}
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref  = "room" }
koin = { group = "io.insert-koin", name = "koin-android", version.ref="koin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

